import { Analytics } from '@vercel/analytics/react'

export const metadata = {
  title: 'CollegeGPT',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
